repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-toml
      - id: check-case-conflict
      - id: debug-statements

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        language_version: python3.13.5

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args: ["--max-line-length=120"]
        additional_dependencies:
          - flake8-annotations
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-docstrings
          # - flake8-isort  #
        language_version: python3.13.5

  # - repo: https://github.com/PyCQA/isort  #
  #   rev: 5.12.0
  #   hooks:
  #     - id: isort
  #       name: isort (python)
  #       types: [python]
  #       args: ["--profile", "black"]
  #       language_version: python3.13.5

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.0
    hooks:
      - id: bandit
        name: bandit
        entry: bash -c 'bandit -q "$@" || true'
        args:
          - --exclude=tests/,migrations/,media/,staticfiles/,venv/,.pixi/
        language: system
        pass_filenames: true
