[workspace]
authors = ["coder-ph <phelixmbani@gmail.com>"]
channels = ["conda-forge"]
name = "Jadwak"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
gdal = ">=3.11.0,<4"
django-environ = ">=0.12.0,<0.13"
psycopg = ">=3.2.9,<4"
