"""alerts/urls.py."""

from rest_framework.routers import DefaultRouter
from django.urls import path, include
from .views import AlertViewSet, AlertRuleViewSet

router = DefaultRouter()
router.register(
    r"alerts", AlertViewSet, basename="alert"
)  # /api/alerts/, /api/alerts/{id}/
router.register(
    r"alert-rules", AlertRuleViewSet, basename="alert-rule"
)  # /api/alert-rules/, /api/alert-rules/{id}/

urlpatterns = [
    path("", include(router.urls)),
    # Custom actions like /api/alerts/{id}/mark-as-read/ are automatically generated by DefaultRouter
]
